export const refs = {
    categoriesList: document.querySelector('.js-categories'),
    productsList: document.querySelector('.js-products'),
    loadMoreBtn: document.querySelector('.js-load-more-btn'),
    searchForm: document.querySelector('.js-search-form'),
    modal: document.querySelector('.js-modal'),
    modalProduct: document.querySelector('.js-modal-product'),
    modalCloseBtn: document.querySelector('.js-modal__close-btn'),
    addToCartModalBtn: document.querySelector('.js-modal-product__btn--cart'),
    addTowishlistBtn: document.querySelector('.js-modal-product__btn--wishlist'),
    cartCountSpan: document.querySelector('[data-cart-count]'),
    wishlistCountSpan: document.querySelector('[data-wishlist-count]'),
    cartProductList: document.querySelector('.products'),
    cartSummaryQ: document.querySelector('[data-count]'),
    cartSummaryPrice: document.querySelector('[data-price]'),
    buyBtnCart: document.querySelector('.js-cart-summary__btn'),
    wishlistProductList: document.querySelector('.js-products-wish'),
    searchFormBtnClear: document.querySelector('.js-search-form__btn-clear'),
    searchInput: document.querySelector('.js-search-form__input'),
    themeToggleBtn: document.querySelector('.js-theme-toggle-btn'),
}